menu:
    Blog: /
    Archive: /archives/
#    Weibo: http://weibo.com/ricolee87
#    GitHub: https://github.com/ascend1
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
